### PR TITLE
new Business Rules node for Bluemix Node-RED

### PR DESCRIPTION
**Pull request by ylecleach**
Hi Dave,
As already mentioned, here is the Business Rules node for Bluemix for your review.
Fell free to contact me.
Yves,
Bluemix Business Rules Team. (ODM)

### CODE REVIEW

**Comment by ylecleach** [comment]
Hi Dave, 
Did you find some time to look at this PR ? What is the next step ?
Thank you.
Bluemix Business Rules Team. (ODM)

**Comment by knolleary** [comment]
@ylecleach my apologies - Dave asked me to sort out the internal process side of this, but the request got lost in my inbox. Getting it sorted out now, will be in touch either later today or early next week.

**Comment by ylecleach** [comment]
Hi Nick, did you manage some time to merge this PR ?
Thank you.
Business Rules for Bluemix Team.

**Comment by knolleary** [comment]
Hi @ylecleach - this was next on my list to look at.

node-red-gitbot: please recheck the CLA status.

@dceejay: over to you for final review & merge

**Comment by dceejay** [comment]
Will do. On vacation until Tues

**Comment by dceejay** [comment]
Hi Yves,
are the paths correct ? It is complaining that the PR conflicts with existing code - which should not be the case as it should all be in a new directory.

**Pull request merged**
