### PR TITLE
added japanese on t2s

### PR DESCRIPTION
**Pull request by moono-jp**
I update watson/t2s.html because I can not select Japanese model on the current file.

### CODE REVIEW

**Comment by jthomas** [comment]
Thanks for submitting this, looks great! 
I'll test this week and then merge.

**Comment by knolleary** [comment]
Please don't forget the CLA requirement before accepting pull requests.
Details in the main repository CONTRIBUTING.MD.

**Comment by jthomas** [comment]
@moono-jp can you follow the steps here?
https://github.com/node-red/node-red/blob/master/CONTRIBUTING.md#pull-requests

**Comment by moono-jp** [comment]
I sent you an e-mail because I am working at IBM. Please let me know the internal CLA process.

**Comment by knolleary** [comment]
Hi,

we've now moved the watson nodes to their own repository: https://github.com/node-red/node-red-node-watson - when you're ready to proceed with this change, please open a pull request against that repository.

Thanks!

**Comment by moono-jp** [comment]
Sure. I talked with the IP department and currently process the internal procedures.

**Pull request closed without merging**
