### PR TITLE
Adding support for the AlchemyAPI nodes and update Watson GA services.

### PR DESCRIPTION
**Pull request by jthomas**

### CODE REVIEW

**Comment by germanattanasio** [comment]
:+1:

**Comment by jthomas** [comment]
I've rebased all the changes into two commits, one to add the Alchemy API nodes and the other with the Watson GA API changes.
:bomb:

**Comment by knolleary** [comment]
Feature Branches James. Feature Branches....

One feature per PR....

Tsk Tsk.

Will look at it later.

**Comment by jthomas** [comment]
I know, I know. 
The changes overlapped with the authentication changes to all the nodes.

**Comment by dceejay** [comment]
Yay ! :+1:

**Pull request merged**
