### PR TITLE
Adding new Watson Nodes

### PR DESCRIPTION
**Pull request by jthomas**
I'd add all the new Watson services and updated the existing ones.

### CODE REVIEW

**Comment by knolleary** [comment]
Sorry it took longer than planned to look at - a few comments before we can merge:

 - need entries adding in `package.json` under `node-red.nodes` for the new nodes - otherwise they won't get picked up. Whilst you're in there, please leave my whitespace alone ;)
 - check the copyright dates in the new files - all new files should be just 2015, modified ones should be `first-year, 2015`
 - squash those commits down

Thanks!

**Comment by jthomas** [comment]
Done, done, done.

**Comment by knolleary** [comment]
:+1: :beers:

**Comment by jthomas** [comment]
💯💯💯

**Pull request merged**
